### ISSUE TITLE
MarketManager.InitAsyc() Error

### ISSUE THREAD

**Issue by OrionRiftStudios** [bmresearch/Solnet.Serum#63]
Following the examples there is an error when I call InitAsync() method 

            _serumClient.ConnectAsync().Wait();
            _marketManager = MarketFactory.GetMarket(new PublicKey(address), serumClient: _serumClient);
            _marketManager.InitAsync().Wait();

NullReferenceException: Object reference not set to an instance of an object.

**Comment by murlokito** [comment]
Are you sure the market adddress is correct?

**Comment by murlokito** [comment]
I haven't been able to replicate this issue from the examples. I will be closing this until there's more context to allow proper debugging, if this reoccurs feel free to reopen.
