### ISSUE TITLE
SerumProgram.CreateMainNet used wrong ProgramIdKey.

### ISSUE THREAD

**Issue by bigsan** [bmresearch/Solnet.Serum#82]
https://github.com/bmresearch/Solnet.Serum/blob/eba508be0e5a777bb7c9d39fa60c78e373cd5e88/Solnet.Serum/SerumProgram.cs#L77

The first argument passed into SerumProgram constructor should be `MainNetProgramIdKeyV3` in `CreateMainNet()`.

**Comment by murlokito** [comment]
Thanks for the heads up on this, I just fixed this for both net5 and net6 and a new release should be up on NuGet shortly.

Appreciate the report and apologies if this caused any issue :)
